### PR TITLE
lint: replace lint/internal/lintutil coerce.go with astcast package

### PR DESCRIPTION
**Pull request by weeellz**
Updates #703.

### CODE REVIEW

**Comment by weeellz** [comment]
I think I'll replace all functions in this PR.

**Comment by Quasilyte** [comment]
@weeellz, okay. :)

Don't forget to remove functions that are no longer used.

**Comment by weeellz** [comment]
@Quasilyte, what to do with `AsUnaryExprOp` which `AsUnaryExprOp is like AsUnaryExpr, but also checks for op token.` There is no replacement function in astcast that checks for op token.

**Comment by Quasilyte** [comment]
> @Quasilyte, what to do with AsUnaryExprOp which AsUnaryExprOp is like AsUnaryExpr, but also checks for op token.?
There is no replacement function in astcast that checks for op token.

Only functions from `corece.go` can be easily replaced.
The function you described can be remained as is.

> And there is IsNil function in coerce.go. What should I do with it?

Can be done in a separate PR if you want to.
Basically:
```go
// before
x := lintutil.AsIdent(a)
return lintutil.IsNil(x)

// after
x := astcast.AsIdent(a)
return x == astcast.NilIdent
```

**Comment by Quasilyte** [comment]
> But AsUnaryExprOp is in coerce.goconfused.

OK, then leave them for now.

**Pull request merged**
