### PR TITLE
checkers/httpNoBody: also warn on using "nil" instead of "http.NoBody" on (net/http/httptest).NewRequest

### PR DESCRIPTION
**Pull request by leonklingele**
Implements https://github.com/go-critic/go-critic/issues/1344.

### CODE REVIEW

**Review by cristaloleg — APPROVED** [review]

**Comment by cristaloleg** [comment]
Thanks for the PR, can you run `go generate ./...` and commit changes?

**Comment by cristaloleg** [comment]
One more fail 🙈 

```
    linttest.go:105: -: # github.com/go-critic/go-critic/checkers/testdata/httpNoBody
Error:         testdata/httpNoBody/negative_tests.go:12:9: assignment mismatch: 2 variables but httptest.NewRequest returns 1 value
Error:         testdata/httpNoBody/positive_tests.go:17:9: assignment mismatch: 2 variables but httptest.NewRequest returns 1 value
Error:     linttest.go:105: /home/runner/work/go-critic/go-critic/checkers/testdata/httpNoBody/negative_tests.go:12:9: assignment mismatch: 2 variables but httptest.NewRequest returns 1 value
Error:     linttest.go:105: /home/runner/work/go-critic/go-critic/checkers/testdata/httpNoBody/positive_tests.go:17:9: assignment mismatch: 2 variables but httptest.NewRequest returns 1 value
```

**Comment by leonklingele** [comment]
Sorry, was working on a system still running Go 1.17, so had to use CI for tests 🙈

Updated, ptal! 🫨🥳

**Comment by cristaloleg** [comment]
Thanks!

**Pull request merged**
