### PR TITLE
update github.com/quasilyte/go-ruleguard to v0.3.4

### PR DESCRIPTION
**Pull request by pierrre**
It's required for `MatchComment`.

Related to https://github.com/golangci/golangci-lint/issues/1923

### CODE REVIEW

**Comment by pierrre** [comment]
I don't know exactly the cause of this failure :thinking:

**Comment by quasilyte** [comment]
GA: everything is bad!
Me: let me try bumping up the Go version
GA: everything is good!

**Review by quasilyte — APPROVED** [review]
LGTM.

**Comment by pierrre** [comment]
thank you very much !

**Comment by pierrre** [comment]
Sorry, I forgot: is it possible to release a new tagged version ?
I would like to update go-critic in golangci-lint.

**Comment by quasilyte** [comment]
Sure.

**Comment by quasilyte** [comment]
https://github.com/go-critic/go-critic/releases/tag/v0.5.6

**Pull request merged**
