### PR TITLE
checkers: add fixable for commentFormatting (#1190)

### LINKED ISSUE #1190: Support autofix for commentFormatting

### PR DESCRIPTION
**Pull request by okhowang**
Fixes #1190

### CODE REVIEW

**Review by cristaloleg — APPROVED** [review]
sgtm

**Comment by quasilyte** [comment]
This will add extra spaces inside comments:
```
//Comment with //inside other comment
=>
// Comment with // inside other comment
```
I don't think that it's a big deal, but it makes it less reliable in general as it does more changes than it should.

**Comment by okhowang** [comment]
> This will add extra spaces inside comments:
> 
> ```
> //Comment with //inside other comment
> =>
> // Comment with // inside other comment
> ```
> 
> I don't think that it's a big deal, but it makes it less reliable in general as it does more changes than it should.

I use `strings.Replace`  with n=1 which mean replace only first `//`

**Comment by quasilyte** [comment]
Ah, that's true.

**Review by quasilyte — APPROVED** [review]

**Pull request merged**
