### PR TITLE
Move tools into own module.

### PR DESCRIPTION
**Pull request by AlekSi**
Closes #34.

### CODE REVIEW

**Review by cristaloleg — APPROVED** [review]

**Comment by cristaloleg** [comment]
Is it exactly #34 ?

**Comment by AlekSi** [comment]
Doh! It is for https://github.com/quasilyte/go-consistent/issues/34

**Review by quasilyte — APPROVED** [review]

**Comment by quasilyte** [comment]
The failure looks unrelated.
It looks like one of the rules gives a different warning location now.
I'll investigate it later.

**Comment by quasilyte** [comment]
Thank you! :tada:

**Pull request merged**
