### PR TITLE
checkers/wrapperFunc: suggest `strings.Cut` instead of `strings.Index`

### PR DESCRIPTION
**Pull request by junk1tm**
This change utilize `strings.Cut`, a new function added in go 1.18, which turned out [quite useful](https://go-review.googlesource.com/c/go/+/351711).

Unfortunately, the current implementation does not cover all cases, e.g. the same examples won't match if the `:=` operator is used instead of `=`. I wonder if we should just copy-paste the same checks with different operators 🤔

Also, a similar function exists in the `bytes` package, so we could implement the `bytes.Index` -> `bytes.Cut` check as well (in another PR, I guess).

### CODE REVIEW

**Review by cristaloleg — APPROVED** [review]
SGTM

**Comment by cristaloleg** [comment]
Yo, can you rebase your changes, please?

**Comment by junk1tm** [comment]
Sure, will do 👍

**Comment by cristaloleg** [comment]
Merged to temp branch, thanks.

**Pull request merged**
