### PR TITLE
Update all_checkers_test.go

### PR DESCRIPTION
**Pull request by Yatheesan**
removed new lines in all_checkers_test.go

### CODE REVIEW

**Comment by Quasilyte** [comment]
Not the kind of newlines I meant in the issue, but I'm OK with this change as well. :)
For the reference, the #701 fixed exactly the thing I described.
Note that I'm still going to merge this PR.

**Comment by Quasilyte** [comment]
@cristaloleg, if you don't mind this PR too, can you press the merge button when CI is finished?
I have to go now.

**Comment by cristaloleg** [comment]
Done, thanks @Yatheesan

**Comment by Quasilyte** [comment]
Also, congrats with completing hacktoberfest challenge. :)

**Pull request merged**
