### PR TITLE
New dupImports checker

### PR DESCRIPTION
**Pull request by Helcaraxan**
Am proposing a new "style" checker that verifies that you are not importing the same package twice in the same Go file under different aliases.

This is not using one of the `astwalk.WalkerFor*` interfaces (which are proxies for `lintpack.FileWalker`) as those do not give access to a file's imports. Instead it directly reimplements the `lintpack.FileWalker` interface itself.

Have added the required positive and negative test files as well.

Example output:
```text
 -> gocritic check -enable=dupImports checkers/testdata/dupImports/positive_tests.go
./checkers/testdata/dupImports/positive_tests.go:4:8: dupImports: package is imported 3 times under different aliases on lines 4, 8 and 10
./checkers/testdata/dupImports/positive_tests.go:8:2: dupImports: package is imported 3 times under different aliases on lines 4, 8 and 10
./checkers/testdata/dupImports/positive_tests.go:10:2: dupImports: package is imported 3 times under different aliases on lines 4, 8 and 10
```

### CODE REVIEW

**Comment by Quasilyte** [comment]
Wow. I like this idea.
I'll do a review in the evening (~10 hours from this moment).
Thanks for doing this. :100:

**Comment by Quasilyte** [comment]
I'll prepare a follow-up PR where all suggestions will be applied.
You'll be CCed into that PR, so it's possible to discuss them.
Thanks.

**Comment by Helcaraxan** [comment]
@Quasilyte which suggestions? 🙂 Sorry. Must be missing some context or have missed messages / comments.

**Comment by Quasilyte** [comment]
We're usually not doing a heavy review, but instead trying to write a lot of tests,  run linters and require both positive and negative tests. If build is green, PR can be merged. If you have style suggestions, you merge the PR, then fix it yourself and notify the author. This way, PRs get merged faster with fewer rounds and efforts from the contributors. It's called optimistic merging, I guess.

**Comment by Helcaraxan** [comment]
Oh. That's fine and had read it in the README. Thought you were referring to comments on this PR itself that I somehow had missed.

Looking forward to your suggestions!

**Pull request merged**
