### PR TITLE
readme: add MacPorts install info

### PR DESCRIPTION
**Pull request by herbygillot**

### CODE REVIEW

**Comment by cristaloleg** [comment]
Hm, why it's empty? 👀  https://ports.macports.org/?search=go-critic&search_by=name

We (as go-critic team) haven't created any MacPorts yet.

**Comment by herbygillot** [comment]
> Hm, why it's empty? 👀 https://ports.macports.org/?search=go-critic&search_by=name

To answer your question, the port for `go-critic` was just added several hours ago, so the MacPorts software catalog at macports.org has not synchronized yet.  It should appear in an hour or two.

> We (as go-critic team) haven't created any MacPorts yet.

I added a port for `go-critic` here: https://github.com/macports/macports-ports/commit/8080641c7c9a3dfb5ce3beab49c802dbff220b4f

Though it's not yet visible on the website, `go-critic` is already available to install via MacPorts:
```
$ port info go-critic
go-critic @0.5.5 (devel)

Description:          The most opinionated Go source code linter for code audit. Highly extensible Go source code linter
                      providing checks currently missing from other linters.
Homepage:             https://github.com/go-critic/go-critic

Build Dependencies:   go
Platforms:            darwin, freebsd, linux
License:              MIT
Maintainers:          Email: herby.gillot@gmail.com, GitHub: herbygillot
                      Policy: openmaintainer
```

**Comment by cristaloleg** [comment]
Oh...that's great! Should we (as go-critic team) do something when we're pushing new (even minor) release? As I've understood it's not automated, am I right? 👀

**Review by cristaloleg — APPROVED** [review]

**Comment by herbygillot** [comment]
> Oh...that's great! Should we (as go-critic team) do something when we're pushing new (even minor) release? As I've understood it's not automated, am I right? 👀

That is correct, it's not automated. It's on me as maintainer to monitor for new releases and update the Portfile.  Also anyone is welcome to open a pull request to update some software's Portfile, but you would need some idea of the Portfile format and also ideally be able to verify in a local MacPorts installation.

**Comment by herbygillot** [comment]
Also `go-critic` has no appeared on macports.org: https://ports.macports.org/port/go-critic/summary

**Comment by cristaloleg** [comment]
Thanks!

**Pull request merged**
