### PR TITLE
rich config format (#574)

### PR DESCRIPTION
**Pull request by ewgRa**
Example of config:

```
{
  "version": 1,
  "checkers": {
    "ifElseChain": {
      "type": "ifElseChain"
    }
  }
}
```

### CODE REVIEW

**Comment by Quasilyte** [comment]
Thanks for working on it.
I'll take a look tomorrow.

**Comment by ewgRa** [comment]
Would be nice to finish with this PR. Looks like here a lot of changes of files that will be touched by golangci/golangci-lint integration https://github.com/golangci/golangci-lint/issues/132#issuecomment-416753725

> Changes on go-critic side: mostly extract criticize command to be able to reuse it for golangci-lint.

Also new Config struct can help in this integration.

**Comment by Quasilyte** [comment]
Sorry for the delay, but this PR isn't forgotten.
Though I've had hard times thinking about it.
I'll try to reach you in Telegram for discussion soon.

**Comment by Quasilyte** [comment]
Now it's possible to include checkers dynamically with plugins, also possible to build a linter with https://github.com/go-lintpack/lintpack with any linter set. There is a simple linter example like https://github.com/Quasilyte/go-police that uses custom config for its purposes.

**Pull request closed without merging**
